# Generated by Django 4.0 on 2022-03-14 12:42

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 14, 17, 42, 3, 240026))),
                ('user', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
