# Generated by Django 4.0 on 2022-03-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
